# This is a supposed SDK given to us by the Anti-Cheat SaaS we are using to get user reputations.
# DO NOT edit this file! Just treat it like a black box.

require 'timeout'
require_relative './errors'

module AntiCheat
  class Client

    TIMEOUT_SECONDS = 10

    def get_reputation(_email) # we're not even using the email, LOL!
      Timeout::timeout(TIMEOUT_SECONDS) do
        buggy_operation
        wait_for_network
        reputation
      end
    end

    private

    def buggy_operation
      raise AntiCheat::RandomError, 'Oops, something went wrong' if error_occurred?
    end

    def error_occurred?
      [*0..10].sample > 8
    end

    def wait_for_network
      sleep network_delay
    end

    def network_delay
      [*0..12].sample
    end

    def reputation
      [*0..100].sample.to_d / 10
    end

  end
end
